### ISSUE TITLE
Encounter FileNotFoundError

### ISSUE THREAD

**Issue by jim60105** [lekoOwO/SuperChatSum#1]
你好，我無法成功使用此專案，提供錯誤資訊如下
測試網址: https://www.youtube.com/watch?v=Dz0ooBrNiag
謝謝

![2021-06-30 00 04 37](https://user-images.githubusercontent.com/16995691/123831307-c6b2cc80-d936-11eb-89ed-36b651a7b746.png)

```Traceback (most recent call last):
  File "E:\repos\SuperChatSum\chat-replay-downloader\chat_replay_downloader.py", line 454, in <module>
    chat_messages = chat_downloader.get_chat_replay(
  File "E:\repos\SuperChatSum\chat-replay-downloader\chat_replay_downloader.py", line 409, in get_chat_replay
    return self.get_youtube_messages(match.group(1), start_time, end_time, message_type)
  File "E:\repos\SuperChatSum\chat-replay-downloader\chat_replay_downloader.py", line 253, in get_youtube_messages
    continuation_by_title_map = self.__get_initial_youtube_info(video_id)
  File "E:\repos\SuperChatSum\chat-replay-downloader\chat_replay_downloader.py", line 158, in __get_initial_youtube_info
    ytInitialData = json.loads(next(line.strip()[len('window["ytInitialData"] = '):-1]
  File "C:\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "E:\repos\SuperChatSum\process.py", line 64, in <module>
    with open(FILE_NAME) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\repos\\SuperChatSum\\output\\4460410d-3443-4a46-b57d-73c11712139b.json'```

**Comment by lekoOwO** [comment]
Due to the break change of Youtube Chat API, the dependency `chat-replay-downloader` has updated their API, thus this project is currently unavailble.

I will update it when I've got some free time, or a PR is welcomed :D
